#!/usr/bin/env bash

# Use this script to generate all the blocklists after `domains.txt` is updated.
# e.g.
# ./update "commit message"

# Cleanup `domains.txt`.
sed -i 's/^www\.//g' domains.txt
cat -n domains.txt | sort -uk2 | sort -nk1 | cut -f2- > domains_temp.txt
mv domains_temp.txt domains.txt

# Generate blocklists from `domains.txt`.
python scripts/domains_to_hosts.py > hosts.txt
python scripts/domains_to_hosts_ipv6.py > hosts.txt.ipv6
python scripts/domains_to_dnsmasq.py > dnsmasq_hosts.txt
python scripts/domains_to_dnsmasq_ipv6.py > dnsmasq_hosts.txt.ipv6
python scripts/domains_to_netsane.py > netsane.txt

# Generate browser extension blocklists.
python scripts/domains_to_adblock.py > adblock_temp.txt
cp adblock_header.txt adblock.txt
cat adblock_temp.txt >> adblock.txt
rm adblock_temp.txt
python scripts/domains_to_ublacklist.py > ublacklist_temp.txt
cp adblock_header.txt ublacklist.txt # Currently using the same adblock header until uBlacklist implements its own header. https://github.com/iorate/ublacklist/issues/351
cat ublacklist_temp.txt >> ublacklist.txt
rm ublacklist_temp.txt